module.exports = {
    ERROR : false,
    SUCCESS : true,
    HTTP_SUCCESS: 200,
    HTTP_CREATED : 201,
    HTTP_ACCEPTED : 202,
    HTTP_BAD_REQUEST: 400,
    HTTP_UN_AUTHORIZED : 401,
    HTTP_FORBIDDEN : 403,
    HTTP_NOT_FOUND : 404,
    HTTP_SERVER_ERROR: 500,
    HTTP_SERVICE_NOT_AVAILABLE: 503
}
